### ISSUE TITLE
Project_index.json does not exist

### ISSUE THREAD

**Issue by swamiforlife** [OpenHypervideo/FrameTrail#27] opened 2018-04-11 05:31 UTC
I have done a clean installation of XAMPP on windows server 2016 and then got the FrameTrail app and created a masterpassword. Then i created a single project but then when i open localhost/Frametrail/ i get No Project.json File error.

what is the problem?

**Comment by hipur** [comment] 2019-02-05 23:18
I'm having the same issue but on a remote server. Did you fix it?

**Comment by OpenHypervideo** [comment] 2019-02-06 09:35
Please try and use the develop branch instead (delete everything before, including the _data directory):
https://github.com/OpenHypervideo/FrameTrail/archive/develop.zip
The project management has been removed entirely, the setup has been simplified a lot and many fixes have been made, but none of this is yet merged into the master branch. Sorry about the inconvenience and let me know if things work with the develop branch.

**Comment by hipur** [comment] 2019-02-06 14:28
Did it, had a problem when first installing but was able to create admin account. Now the page it shows after is blank and Chrome shows the following error:

Query.Deferred exception: FrameTrail.init is not a function TypeError: FrameTrail.init is not a function
    at HTMLDocument.<anonymous> (http://video.rodrigoebeta.com/:166:48)
    at j (http://video.rodrigoebeta.com/_lib/jquery/jquery-3.1.1.min.js:2:29948)
    at k (http://video.rodrigoebeta.com/_lib/jquery/jquery-3.1.1.min.js:2:30262) undefined
r.Deferred.exceptionHook @ jquery-3.1.1.min.js:2
jquery-3.1.1.min.js:2 Uncaught TypeError: FrameTrail.init is not a function
    at HTMLDocument.<anonymous> ((index):166)
    at j (jquery-3.1.1.min.js:2)
    at k (jquery-3.1.1.min.js:2)

**Comment by OpenHypervideo** [comment] 2019-02-06 14:37
Hmm, when I visit http://video.rodrigoebeta.com/, I see no errors (neither in Chrome nor in Firefox). I can create an account and also managed to login without any problems. If it says FrameTrail.init is not a function, that could mean that the JS files are not correctly referenced. This might result from another installation of eg. Wordpress, which enforces rwdirect rules for scripts. But right now I can't reproduce the problem, as everything seems to work correctly when I visit your installation. Can you upload images or a test video? (login -> folder icon on the top right)

**Comment by hipur** [comment] 2019-02-06 14:41
Sure.
I just got it working fine on Microsoft Edge though...

Is it possible to increase the file upload limit from 128mb to 1gb?

**Comment by OpenHypervideo** [comment] 2019-02-06 14:47
Great. Yes that's possible, but it doesn't depend on FrameTrail. It's actually a server setting. FrameTrail tries to increase this setting here: https://github.com/OpenHypervideo/FrameTrail/blob/develop/.htaccess#L33, but that only works if your server allows that. Try this instruction (Method 1, as Method 2 doesn't work on your server). There's unfortunately nothing we can do about that. That's totally up to your server.

**Comment by OpenHypervideo** [comment] 2019-05-23 15:20
solved in new version

**Closed by OpenHypervideo** 2019-05-23 15:20 UTC

**Comment by hipur** [comment] 2019-06-17 17:39
I've tried to install the new version and got the same error. :(

**Comment by OpenHypervideo** [comment] 2019-06-18 07:31
That would be strange. The most recent versions don't even have the project management anymore. Did you install the development branch? (delete everything before, including the _data directory):
https://github.com/OpenHypervideo/FrameTrail/archive/develop.zip
I was able to access your installation before and couldn't see any problems. There will be a new "proper" version soon. Right now everything is in a state of limbo because of parallel developments which first need to be properly merged into the master repository.

**Comment by hipur** [comment] 2019-06-24 14:26
Guess I didn't installed the development branch. I'm sorry.
