### ISSUE TITLE
Docker Permissions Error

### ISSUE THREAD

**Issue by edsilv** [OpenHypervideo/FrameTrail#25] opened 2017-12-24 12:00 UTC
I'm working on this Dockerfile: https://github.com/edsilv/frametrail-now-deploy/blob/master/Dockerfile

It's deploying to now.sh, but when navigating to /FrameTrail I get:

![image](https://user-images.githubusercontent.com/1334393/34326330-956f168a-e8a1-11e7-87ec-da818cffa0ac.png)

As you can see I'm setting everything under /var/www to 755 and creating a _data directory. A bit stumped!

**Comment by OpenHypervideo** [comment] 2017-12-26 09:10
Hi Ed! That's indeed strange. It fails right here: https://github.com/OpenHypervideo/FrameTrail/blob/master/_server/ajaxServer.php#L204, which it shouldn't (http://php.net/manual/en/function.is-writable.php). You may try setting 755 to the FrameTrail root without generating the "_data" directory manually. But in both cases, it should just work. I'm not entirely sure right now if the check (is_writable on the root dir) is correct and should be performed every time, even if there already is a writable "_data" dir. Will do some tests asap, but may not be able to do so before the new year ;)

**Comment by OpenHypervideo** [comment] 2017-12-26 09:50
Alright, went through the setup check again and adjusted the writable directory checks + respective error messages: https://github.com/OpenHypervideo/FrameTrail/commit/6259668f978bc720324748d6c07addec4b6b8ce8. Please try again and tell me if it still fails.

**Comment by edsilv** [comment] 2017-12-26 11:42
Still no luck I'm afraid. If I don't manually create the _data directory I get the same error as before:

![image](https://user-images.githubusercontent.com/1334393/34355257-d8d7ee48-ea2b-11e7-8425-9d6d555bb584.png)

If I create it manually I get this:

![image](https://user-images.githubusercontent.com/1334393/34355085-ba2570e8-ea2a-11e7-9a17-727d33c12ea0.png)

Maybe I'm doing something wrong when setting permissions in docker?

https://serverfault.com/questions/772227/chmod-not-working-correctly-in-docker

I tried this but still get the same error:

```
FROM php:apache

RUN apt-get update
RUN apt-get install -y git
RUN mkdir /temp && cd /temp && git clone https://github.com/OpenHypervideo/FrameTrail
RUN rm -rf /var/www/html && mv /temp/FrameTrail/ /var/www/html &&\
    chmod -R 755 /var/www/html

EXPOSE 80

CMD apachectl -D FOREGROUND
```

**Comment by OpenHypervideo** [comment] 2018-01-03 10:54
I now tested it in different server and localhost environments (without a Docker container though). As long as the permissions are set correctly (either automatically via PHP or manually via CHMOD), it works. Unfortunately I have no experience working with Docker, let alone setting directory permissions. But it is definitely a Docker issue as the PHP part is pretty straight forward. You can try removing the check entirely (https://github.com/OpenHypervideo/FrameTrail/commit/6259668f978bc720324748d6c07addec4b6b8ce8). Maybe the permissions are set correctly and it's just the "is_writable()" method that fails for some reason? That would be even more strange though. If that doesn't do the trick I guess you need to consult a Docker pro. Sorry about that.

**Comment by edsilv** [comment] 2018-01-03 11:55
Ok, this is what I've got now: https://github.com/edsilv/frametrail-now-deploy/blob/master/Dockerfile
I realised the extra `RUN`s were causing 'Intermediate Containers' to be used unnecessarily.
I'm checking out your commit, but still getting this:

![image](https://user-images.githubusercontent.com/1334393/34519464-020a1e2a-f07c-11e7-8101-a8ceb86f286c.png)

**Comment by OpenHypervideo** [comment] 2018-01-03 12:49
Ok, as said before, I have no idea of Docker. But what I found is that it could have something to do with the user / group setting (Docker using "staff", PHP using "www-data" / user ID "33").  Several solutions to similar problems (mostly in OS X environments) contain hints to either `CHOWN` or `usermod`, so maybe the `CHMOD` setting is not enough:
https://stackoverflow.com/a/36131792
https://www.reddit.com/r/docker/comments/6lmkgz/a_php_docker_permission_problem/djw7wk5/
https://serverfault.com/a/652852
https://github.com/boot2docker/boot2docker/issues/587#issuecomment-114868208
https://codedump.io/share/2SRjIwcZiop8/1

**Comment by edsilv** [comment] 2018-01-03 13:37
Yeah, adding `chown www-data:www-data -R /var/www/html` seems to have fixed it! Thanks @rhodesy 
However, now getting a new error after creating a project:

![image](https://user-images.githubusercontent.com/1334393/34522572-228da388-f08b-11e7-904b-d14e312d9eff.png)

**Comment by OpenHypervideo** [comment] 2018-01-03 13:47
Have you accessed that screen via the link in the Project Manager (where you created the project), or did you manually type in the url? Because the first project id in a fresh install should automatically be `1`, not `0`.

**Comment by edsilv** [comment] 2018-01-03 13:49
It failed when creating it in the project manager, so I refreshed. Here's the link to `1`: https://frametrail-now-deploy-yvnfwdozlu.now.sh/player/?project=1

**Comment by edsilv** [comment] 2018-01-03 13:50
Sent you the password on Skype

**Comment by OpenHypervideo** [comment] 2018-01-03 14:04
I need to look at that more deeply later. The project seems to have been created correctly: https://frametrail-now-deploy-yvnfwdozlu.now.sh/_data/projects/1/project.json. However, in the project index file (https://frametrail-now-deploy-yvnfwdozlu.now.sh/_data/projects/_index.json), the data doesn't make sense. It should look like this:

`{
    "projects": {
        "1": "./1"
    },
    "project-increment": 1
}`

That's maybe the reason the project creation failed in the first place.
If you want to have a look yourself, this is where the new project is created:
https://github.com/OpenHypervideo/FrameTrail/blob/master/_server/projects.php#L74

I've never seen this fail before, so I suspect it is also somehow attached to the Docker environment. Or it is some strange PHP JSON encode / decode error. I'll have a look as soon as I can.

**Comment by OpenHypervideo** [comment] 2018-01-03 14:18
@tammo0 any idea why this could happen?

**Comment by tammo0** [comment] 2018-01-05 12:54
@edsilv @OpenHypervideo 
As long as i can't see the phpinfo and access the logs its difficult for me because i can't reproduce your case. Seems to be a problem with an undefined variable.

I'ld suggest to replace
`"$projects["project-increment"]++;"`
with 
`$projects["project-increment"] = (($projects["project-increment"]) ? $projects["project-increment"]++ : 1);`
atline 102 of the file "_server/projects.php" (https://github.com/OpenHypervideo/FrameTrail/blob/master/_server/projects.php#L102)

**Comment by edsilv** [comment] 2018-01-05 16:19
Here's the phpinfo: https://frametrail-now-deploy.now.sh/phpinfo.txt

If you fork https://github.com/edsilv/frametrail-now-deploy you should just need to change the alias to something else in `now.json` to test it.

**Comment by edsilv** [comment] 2018-03-14 14:38
@tammo0 I tried that on a fork and still getting 

> No project.json file

**Comment by OpenHypervideo** [comment] 2020-02-20 08:40
Closing as "project" concept has been removed entirely in the new version: https://github.com/OpenHypervideo/FrameTrail/releases/tag/v0.9.6-beta. Directory permissions might still be an issue with docker containers, if yes please file a new issue.

**Closed by OpenHypervideo** 2020-02-20 08:40 UTC
